### ISSUE TITLE
Enable Python 3.9 and 3.10

### ISSUE THREAD

**Issue by zklaus** [SciTools-incubator/iris-esmf-regrid#161] opened 2022-03-08 14:29 UTC
## ✨ Feature Request

It would be great if we could get Python 3.9 and Python 3.10 builds for iris-esmf-regrid. At the moment, the maximum version is 3.8, but it is unclear to me whether that is simply because that was the version available when the CI was setup or for a deeper reason.

Does anyone know?

**Comment by trexfeathers** [comment] 2022-03-08 14:37
@zklaus we're currently held up by iris#4465, which is a barrier to advancing Iris (and therefore iris-esmf-regrid too) beyond 3.8.

**Comment by zklaus** [comment] 2022-03-08 16:46
Thanks, @trexfeathers for the explanation. However, Iris itself doesn't seem to draw the same conclusion and installs happily in 3.9 and 3.10.

**Comment by trexfeathers** [comment] 2022-03-08 16:48
@zklaus the problem is that we're unable to run Iris' test suite `>3.8`, so we therefore can't officially support `>3.8` ☹

**Comment by zklaus** [comment] 2022-03-08 16:50
I understand. But nevertheless, iris installs in 3.9 and 3.10 environments, so I don't think that should be grounds for iris-esmf-regrid to forbid it.

**Comment by trexfeathers** [comment] 2022-06-07 08:40
@stephenworsley thoughts?

**Comment by stephenworsley** [comment] 2022-09-09 08:05
Since iris now has these requirements files, these can be added to iris-esmf-regrid without any problem.

**Comment by zklaus** [comment] 2022-09-16 15:44
My understanding is that this was fixed with #208, right?

Thanks, @stephenworsley, @trexfeathers! :tada:

**Comment by stephenworsley** [comment] 2022-09-20 08:15
Closed by #208

**Closed by stephenworsley** 2022-09-20 08:15 UTC
Labels: New: Feature
